apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        cns-ubiwhere/golang-test: true
        cns-ubiwhere/golang-test3: true
        cns-ubiwhere/golang-test4: true
        cns-ubiwhere/jx3: true
        cns-ubiwhere/quickstart-node: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        cns-ubiwhere/golang-test: merge
        cns-ubiwhere/golang-test3: merge
        cns-ubiwhere/golang-test4: merge
        cns-ubiwhere/jx3: merge
        cns-ubiwhere/quickstart-node: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - cns-ubiwhere/jx3
        - cns-ubiwhere/golang-test
        - cns-ubiwhere/golang-test3
        - cns-ubiwhere/golang-test4
        - cns-ubiwhere/quickstart-node
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - cns-ubiwhere/jx3
        - cns-ubiwhere/golang-test
        - cns-ubiwhere/golang-test3
        - cns-ubiwhere/golang-test4
        - cns-ubiwhere/quickstart-node
      target_url: http://lighthouse-jx.jx.snob.ubiwhere.com/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
